server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: work
          uri: http://localhost:8082
          predicates:
            - Path=/workOrders/**, 
        - id: accountInfo
          uri: http://localhost:8083
          predicates:
            - Path=/accountInfos/**, 
        - id: workType
          uri: http://localhost:8084
          predicates:
            - Path=/workTypes/**, 
        - id: policyChecker
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: userInfo
          uri: http://localhost:8086
          predicates:
            - Path=/userInfos/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: work
          uri: http://work:8080
          predicates:
            - Path=/workOrders/**, 
        - id: accountInfo
          uri: http://accountInfo:8080
          predicates:
            - Path=/accountInfos/**, 
        - id: workType
          uri: http://workType:8080
          predicates:
            - Path=/workTypes/**, 
        - id: policyChecker
          uri: http://policyChecker:8080
          predicates:
            - Path=, 
        - id: userInfo
          uri: http://userInfo:8080
          predicates:
            - Path=/userInfos/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
