---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: work
  labels:
    app: work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
        - name: work
          image: username/work:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountInfo
  labels:
    app: accountInfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountInfo
  template:
    metadata:
      labels:
        app: accountInfo
    spec:
      containers:
        - name: accountInfo
          image: username/accountInfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: workType
  labels:
    app: workType
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workType
  template:
    metadata:
      labels:
        app: workType
    spec:
      containers:
        - name: workType
          image: username/workType:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: policyChecker
  labels:
    app: policyChecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policyChecker
  template:
    metadata:
      labels:
        app: policyChecker
    spec:
      containers:
        - name: policyChecker
          image: username/policyChecker:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userInfo
  labels:
    app: userInfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userInfo
  template:
    metadata:
      labels:
        app: userInfo
    spec:
      containers:
        - name: userInfo
          image: username/userInfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: work
  labels:
    app: work
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: work


---


apiVersion: v1
kind: Service
metadata:
  name: accountInfo
  labels:
    app: accountInfo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: accountInfo


---


apiVersion: v1
kind: Service
metadata:
  name: workType
  labels:
    app: workType
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: workType


---


apiVersion: v1
kind: Service
metadata:
  name: policyChecker
  labels:
    app: policyChecker
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: policyChecker


---


apiVersion: v1
kind: Service
metadata:
  name: userInfo
  labels:
    app: userInfo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: userInfo

